#!/bin/bash


PORT_DIR=/usr/portage
PORT_SQUASH="$( find /dev/mapper -iname '*portage' | head -n 1 )"

function my_umount () {

	if [ -n "$(mount | grep $1)" ]; then
		umount "$1" && return 0 || \
		echo "Error unmounting $1" && exit -1
	fi

}

function my_mount_tmpfs () {
	# Liberal parameters; these are only around for a few seconds.
	my_umount "$1" &&\
	mount -t tmpfs -o size=768M,nr_inodes=250000 tmpfs "$1"
}

function my_repack () {
	if ! (time mksquashfs $1 /tmp/portage.sfs -no-xattrs -no-progress && \
	dd if=/tmp/portage.sfs of=$PORT_SQUASH bs=1M && \
    rm /tmp/portage.sfs); then
	echo "Error repacking ${2}." && exit -1; fi

}

function lay () {
	if [ -n "$1" ]
	then
		layman -f
		layman -S
	fi
}

function open () {
	my_mount_tmpfs $PORT_DIR && \
	time unsquashfs -n -no -f -d $PORT_DIR $PORT_SQUASH
}

function close () {
	my_repack $PORT_DIR $PORT_SQUASH &&\
	umount $PORT_DIR &&\
	mount $PORT_DIR
}

function sync () {

	open && \
	layman -S &&\
	emerge --sync &&\
	close ||\
	echo "Error, sync incomplete.  Investigate."
}

function help () {
	echo "sync"
}

$@
