#!/bin/bash

SQUASHFS_DIR=/root/fs

PORT_DIR=/usr/portage
PORT_SQUASH="$SQUASHFS_DIR/portage.sfs"

function my_umount () {	

	if [ -n "$(mount | grep $1)" ]; then
		umount "$1" && return 0 || \
		echo "Error unmounting $1" && exit -1
	fi

}

function my_mount_tmpfs () {
	# Liberal parameters; these are only around for a few seconds.
	my_umount "$1" &&\
	mount -t tmpfs -o size=768M,nr_inodes=250000 tmpfs "$1"
}

function my_repack () {
	
	rm -f ${2}.tmp
	if ! (mksquashfs $1 ${2}.tmp && \
        chmod a+r ${2}.tmp && \
	mv ${2}.tmp ${2}); then
	echo "Error repacking ${2}." && exit -1; fi

}

function lay () {
	if [ -n "$1" ]
	then
		layman -f
		layman -S
	fi
}

function open () {
	my_mount_tmpfs $PORT_DIR && \
	unsquashfs -f -d $PORT_DIR $PORT_SQUASH
}

function close () {
	my_repack $PORT_DIR $PORT_SQUASH &&\
	umount $PORT_DIR &&\
	mount $PORT_DIR
} 

function sync () {

	open && \
	layman -S &&\
	emerge --sync &&\
	echo "Sleeping 10s for user activity..." &&\
	sleep 10 &&\
	close ||\
	echo "Error, sync incomplete.  Investigate."
}

function help () {
	echo "sync"
}

$@
