#!/usr/bin/python

import paramiko, dialog, os, sys, stat, time, subprocess

def getf(d, s, fn):
    if sys.argv[-1] == '-i':
        bleg = 'i'
    else:
        bleg = 'c'
    try:
        limit = str(int(sys.argv[1]))
    except:
        limit = '8000'
    path = "osiris.local:d/%s/%s" % (bleg, fn)
    subprocess.call([
        'rsync', '-rPztSs', '--bwlimit', limit,
        '--exclude', '*r[0123456789][0123456789]',
        '--exclude', 'Sample', '--timeout', '20', path, '.'])
    def remain():
        sub = subprocess.Popen(['rsync', '-rzsin', path, '.'],
                               stdout=subprocess.PIPE)
        stdout, stderr = sub.communicate()
        if sub.returncode:
            raise EnvironmentError("rsync call failed")
        return bool(stdout)
    while remain():
        subprocess.call([
            'rsync', '-rPzts', '--bwlimit', limit, '--sparse', '--chmod=+rX',
            '--timeout', '20', path, '.'])

def nuke(s, fn):
    print 'Removing ' + fn
    st = s.stat(fn)
    if stat.S_ISDIR(st.st_mode):
        ls = sorted(s.listdir(fn))
        for subfn in ls:
            nuke(s, os.path.join(fn, subfn))
        s.rmdir(fn)
    else:
        s.remove(fn)

try:
    d = dialog.Dialog()
    c = paramiko.SSHClient()
    c.load_system_host_keys()
    c.connect('ninjacomputer.com', username='steven')
    s = c.open_sftp()
    print sys.argv
    if sys.argv[-1] == '-i':
        s.chdir('/home/steven/d/i')
        l = sorted(s.listdir_attr(), key = lambda k: -k.st_mtime)[:100]
        ls = map(lambda o: o.filename, l)
    else:
        s.chdir('/home/steven/d/c')
        ls = sorted(s.listdir())
    if len(ls) == 0:
        print ("No files in remote directory!")
        sys.exit(0)
    choices = [ (str(i), fn, 0) for (i, fn) in enumerate(ls) ]
    (exit, selected) = d.checklist(text="Select a file / directory",
                                   list_height = 15, choices = choices,
                                   width = 90, height = 22)

    for i_s in selected:
        i = int(i_s)
        getf(d, s, ls[i])
        if sys.argv[-1] != '-i':
            nuke(s, ls[i])

except:
    c.close()
    raise

c.close()
sys.exit(0)

